# Generated by Django 5.2.11 on 2026-03-22 20:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_item_myapp_item_item_na_8fffba_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='item',
            name='myapp_item_item_na_8fffba_idx',
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name', 'item_price', 'user_name'], name='myapp_item_item_na_92f157_idx'),
        ),
    ]
