# Generated by Django 5.2.11 on 2026-04-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_item_deleted_at_item_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.URLField(default='https://i.etsystatic.com/51974854/r/il/117305/6435886527/il_1080xN.6435886527_3k6v.jpg', max_length=505),
        ),
    ]
